const products=[
    {
        _id:"1",
        name:"Nike slim Shirt",
        category:"shirts",
        image:"./images/p1.jpg",
        Brand:"Nike",
        Price:120,
        ratings:4.5,
        numReviews:10,
        description:"Best quality Shirts",
        countInStock:3,
    },
    {
        _id:"2",
        name:"adidas fit Shirt",
        category:"shirts",
        image:"./images/p2.jpg",
        Brand:"adidas",
        Price:110,
        ratings:5,
        numReviews:10,
        description:"Best quality Shirts",
        countInStock:3,
    },
    {
        _id:"3",
        name:"lacote slim Shirt",
        category:"shirts",
        image:"./images/p3.jpg",
        Brand:"lacote",
        Price:100,
        ratings:3.5,
        numReviews:10,
        description:"Best quality Shirts"
    },
    {
        _id:"4",
        name:"Nike slim pants",
        category:"pants",
        image:"./images/p4.jpg",
        Brand:"Nike",
        Price:90,
        ratings:5,
        numReviews:10,
        description:"Best quality pants",
        countInStock:3,
    },
    {
        _id:"5",
        name:"adidas slim pants",
        category:"pants",
        image:"./images/p5.jpg",
        Brand:"adidas",
        Price:125,
        ratings:4.5,
        numReviews:10,
        description:"Best quality pants",
        countInStock:3,
    },
    {
        _id:"6",
        name:"lacoste slim pants",
        category:"pants",
        image:"./images/p6.jpg",
        Brand:"lacoste",
        Price:130,
        ratings:5,
        numReviews:10,
        description:"Best quality pants",
        countInStock:3,
    }
]

export default products;